"""setup_directory_tables

Revision ID: 4c6f4416435a
Revises: 6ffe1a051957
Create Date: 2026-01-17 23:21:48.410444

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c6f4416435a"
down_revision: Union[str, Sequence[str], None] = "6ffe1a051957"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buildings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="Уникальный идентификатор записи"),
        sa.Column("address", sa.String(length=255), nullable=False, comment="Адрес здания"),
        sa.Column("latitude", sa.Float(), nullable=False, comment="Широта"),
        sa.Column("longitude", sa.Float(), nullable=False, comment="Долгота"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
        sa.UniqueConstraint("latitude", "longitude", name="uq_building_lat_lon"),
        schema="directory",
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="Уникальный идентификатор записи"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Название категории (деятельности)"),
        sa.Column("base_category_id", sa.Integer(), nullable=True, comment="ID базовой категории (родителя)"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.ForeignKeyConstraint(
            ["base_category_id"],
            ["directory.categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="directory",
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="Уникальный идентификатор записи"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Название организации"),
        sa.Column("building_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.ForeignKeyConstraint(["building_id"], ["directory.buildings.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="directory",
    )
    op.create_table(
        "organization_category",
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["directory.categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["directory.organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("organization_id", "category_id"),
        schema="directory",
    )
    op.create_table(
        "phones",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="Уникальный идентификатор записи"),
        sa.Column("phone", sa.String(length=20), nullable=False, comment="Номер телефона"),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["directory.organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="directory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("phones", schema="directory")
    op.drop_table("organization_category", schema="directory")
    op.drop_table("organizations", schema="directory")
    op.drop_table("categories", schema="directory")
    op.drop_table("buildings", schema="directory")
    # ### end Alembic commands ###
